export enum feedConstant {
    CARDS_HAS_ERRORED = 'CARDS_HAS_ERRORED',
    CARDS_IS_LOADING = 'CARDS_IS_LOADING',
    CARDS_FETCH_DATA_SUCCESS = 'CARDS_FETCH_DATA_SUCCESS',

    TAGS_HAS_ERRORED = 'TAGS_HAS_ERRORED',
    TAGS_IS_LOADING = 'TAGS_IS_LOADING',
    TAGS_FETCH_DATA_SUCCESS = 'TAGS_FETCH_DATA_SUCCESS',

    INSTAGRAM_SUCCESS = 'INSTAGRAM_SUCCESS',
    INSTAGRAM_IS_LOADING = 'INSTAGRAM_IS_LOADING',
    INSTAGRAM_FAILURE = 'INSTAGRAM_FAILURE',

    VK_SUCCESS = 'VK_SUCCESS',
    VK_IS_LOADING = 'VK_IS_LOADING',
    VK_FAILURE = 'VK_FAILURE',

    TWITTER_SUCCESS = 'TWITTER_SUCCESS',
    TWITTER_IS_LOADING = 'TWITTER_IS_LOADING',
    TWITTER_FAILURE = 'TWITTER_FAILURE',

    LOAD_MORE = 'LOAD MORE'
}