export enum feedConstant {
    CARDS_HAS_ERRORED = 'CARDS_HAS_ERRORED',
    CARDS_IS_LOADING = 'CARDS_IS_LOADING',
    CARDS_FETCH_DATA_SUCCESS = 'CARDS_FETCH_DATA_SUCCESS',

    TAGS_HAS_ERRORED = 'TAGS_HAS_ERRORED',
    TAGS_IS_LOADING = 'TAGS_IS_LOADING',
    TAGS_FETCH_DATA_SUCCESS = 'TAGS_FETCH_DATA_SUCCESS',

    INSTAGRAM_SUCCESS = 'INSTAGRAM_SUCCESS',
    INSTAGRAM_FAILURE = 'INSTAGRAM_FAILURE'
}